import { jsPDF } from "jspdf";
import { APP_NAME, APP_VERSION, MODEL_NAME } from "../../constants/config";
import type { AnalysisReport } from "../../types";
import { formatFileSize, formatTimestamp } from "../utils/format";
import { isAiPrediction } from "../utils/prediction";

export function generatePdfReport(report: AnalysisReport): void {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const isAi = isAiPrediction(report.result.prediction);
  const accent = isAi ? [239, 68, 68] : [16, 185, 129];

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 120, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(APP_NAME, margin, 48);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Detection Report · v${APP_VERSION}`, margin, 68);
  doc.text(formatTimestamp(report.timestamp), margin, 84);

  y = 150;

  const section = (title: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(59, 130, 246);
    doc.text(title.toUpperCase(), margin, y);
    y += 18;
  };

  const row = (label: string, value: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(label, margin, y);
    doc.setTextColor(30, 41, 59);
    doc.text(value, margin + 120, y);
    y += 16;
  };

  section("Classification Result");
  doc.setFillColor(accent[0], accent[1], accent[2]);
  doc.roundedRect(margin, y, contentWidth, 56, 6, 6, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(report.result.prediction, margin + 16, y + 24);
  doc.setFontSize(12);
  doc.text(`Confidence: ${report.result.confidence}%`, margin + 16, y + 44);
  y += 72;

  section("Analysis Summary");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(report.summary, contentWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 14 + 12;

  section("File Details");
  row("Filename", report.file.name);
  row("Size", formatFileSize(report.file.size));
  row("Type", report.file.type);
  row("Dimensions", report.file.width && report.file.height ? `${report.file.width} × ${report.file.height}px` : "N/A");
  row("Last Modified", formatTimestamp(new Date(report.file.lastModified).toISOString()));
  y += 8;

  section("Risk Metrics");
  row("Risk Level", report.riskLevel);
  row("Signal Strength", report.signalStrength);
  row("Model", MODEL_NAME);
  row("Report ID", report.id);

  y += 16;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Disclaimer: This report is generated by an AI classification model and is intended for informational purposes only.",
    margin,
    y,
    { maxWidth: contentWidth }
  );

  const safeName = report.file.name.replace(/\.[^/.]+$/, "");
  doc.save(`${safeName}-detection-report.pdf`);
}
